default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 200
  port: 3306
  host: localhost
  username: root
  password: 666666

development:
  primary:
    <<: *default
    database: xigua

production:
  primary:
    <<: *default
    database: xigua
